name: mental_health_app
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
